### ISSUE TITLE
Bug: won't import

### ISSUE THREAD

**Issue by Moosems** [tree-sitter-grammars/tree-sitter-arduino#30]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

Cannot import from python. Despite the error message, the source binding looks fine.

```bash
$ rm test.py
$ echo "from tree_sitter_arduino import language as arduino_language" > test.py
$ pip uninstall tree-sitter-arduino -y
Found existing installation: tree-sitter-arduino 0.21.1
Uninstalling tree-sitter-arduino-0.21.1:
  Successfully uninstalled tree-sitter-arduino-0.21.1
$ pip install tree-sitter-arduino
Collecting tree-sitter-arduino
  Using cached tree_sitter_arduino-0.21.1-cp38-abi3-macosx_10_9_x86_64.whl.metadata (2.0 kB)
Using cached tree_sitter_arduino-0.21.1-cp38-abi3-macosx_10_9_x86_64.whl (278 kB)
Installing collected packages: tree-sitter-arduino
Successfully installed tree-sitter-arduino-0.21.1

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
$ python test.py
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/salve-dependency-hub/test.py", line 1, in <module>
    from tree_sitter_arduino import language as arduino_language
  File "/Users/Moosems/Desktop/salve-dependency-hub/venv/lib/python3.12/site-packages/tree_sitter_arduino/__init__.py", line 3, in <module>
    from ._binding import language
ImportError: dynamic module does not define module export function (PyInit__binding)
```

### Steps To Reproduce/Bad Parse Tree

Run the shell script (copied from above): `rm test.py; echo "from tree_sitter_arduino import language as arduino_language" > test.py; pip uninstall tree-sitter-arduino -y; pip install tree-sitter-arduino; python test.py`. 

### Expected Behavior/Parse Tree

It imports?

### Repro

See above

**Comment by ObserverOfTime** [comment]
Is this issue still present in 0.23.0?

**Comment by Moosems** [comment]
Nope!
